name: 'Run and upload unit tests'
description: 'Run unit tests using pytest and upload the results as an artifact.'
runs:
  using: "composite"
  steps:
    - name: Get OS version
      run: echo "osVersion=$ImageOS" >> "$GITHUB_ENV"
      shell: bash
    - name: Cache ni.datastore virtualenv
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./.venv
        key: ni.datastore-${{ runner.os }}-py${{ env.pythonVersion }}-${{ hashFiles('./poetry.lock') }}
    - name: Install ni.datastore
      run: poetry install -v
      working-directory: .
      shell: bash
    - name: Run ni.datastore unit tests and code coverage
      run: poetry run pytest ./tests/unit -v --cov=ni.datastore --junitxml=test_results/ni.datastore-${{ env.osVersion }}-py${{ env.pythonVersion }}.xml
      working-directory: .
      shell: bash
    - name: Upload ni.datastore test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: test_results_unit_ni.datastore_${{ env.osVersion }}_py${{ env.pythonVersion }}
        path: ${{ github.workspace }}/test_results/*.xml
      if: always()