Introduction
============

About
-----

The ``ni.datastore`` Python package provides APIs for publishing and retrieving data from the NI Measurement Data Store

NI created and supports this package.

Operating System Support
------------------------

``ni.datastore`` supports Windows and Linux operating systems.

Python Version Support
----------------------

``ni.datastore`` supports CPython 3.10+.

Installation
------------

As a prerequisite to using the ``ni.datastore`` module, you must install Measurement Data Services
Software 2026 Q1 or later on your system. You can download and install this software using
NI Package Manager.

You can directly install the ``ni.datastore`` package using ``pip`` or by listing it as a dependency in
your project's ``pyproject.toml`` file.