Introduction
============

About
-----

The ``ni.datastore`` Python package provides APIs for publishing and retrieving data from the NI Measurement Data Store

NI created and supports this package.

Operating System Support
------------------------

``ni.datastore`` supports Windows and Linux operating systems.

Python Version Support
----------------------

``ni.datastore`` supports CPython 3.9+.

Installation
------------

You can directly install the ``ni.datastore`` package using ``pip`` or by listing it as a dependency in
your project's ``pyproject.toml`` file.